### ISSUE TITLE
Old README file

### ISSUE THREAD

**Issue by AndresRoc** [JomanDiec/popcorn-robot#1]
The libraries required to execute this repository are not specified.
Current error:
`` 
ERRORS:
ask_it.Ask_it.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
ask_it.QuestionImage.cover: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.org/project/Pillow/ or run command "python -m pip install Pillow".
``

**Comment by AndresRoc** [comment]
> The libraries required to execute this repository are not specified.

**Comment by JomanDiec** [comment]
updated
